#ifndef LIBEMERGENCYCENTER_GLOBAL_H
#define LIBEMERGENCYCENTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBEMERGENCYCENTER_LIBRARY)
#  define LIBEMERGENCYCENTER_EXPORT Q_DECL_EXPORT
#else
#  define LIBEMERGENCYCENTER_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBEMERGENCYCENTER_GLOBAL_H
